=== memotoro/xml-projects/xml-projects/xquery-wxs-project/el.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified"
  targetNamespace="http://www.cs.manchester.ac.uk/pgt/COMP60411/el"
  xmlns:el="http://www.cs.manchester.ac.uk/pgt/COMP60411/el">
  <xs:element name="dltheory">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="el:author" />
        <xs:element ref="el:last-revised-on"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:group ref="el:Axiom"/>
          <xs:group ref="el:Annotation"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="author" type="xs:string"/>
  <xs:element name="last-revised-on" type="xs:date"/>
  <xs:group name="Annotation">
    <xs:choice>
      <xs:element ref="el:comment" />
      <xs:element ref="el:web-source"/>
    </xs:choice>
  </xs:group>
  
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="web-source" type="xs:anyURI"/>
  <xs:group name="Axiom">
    <xs:choice>
      <xs:element ref="el:equivalent"/>
      <xs:element ref="el:subsumes"/>
      <xs:element ref="el:instance-of"/>
      <xs:element ref="el:related-to"/>
    </xs:choice>
  </xs:group>

  <xs:group name="ClassExpression">
    <xs:choice>
      <xs:element ref="el:atomic"/>
      <xs:element ref="el:conjunction"/>
      <xs:element ref="el:exists"/>
    </xs:choice>
  </xs:group>

  <xs:group name="Entities">
    <xs:choice>
      <xs:element ref="el:atomic"/>
      <xs:element ref="el:constant"/>
    </xs:choice>
  </xs:group>

  <xs:element name="equivalent">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="2" maxOccurs="unbounded" ref="el:ClassExpression"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="subsumes">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="2" maxOccurs="2" ref="el:ClassExpression"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="instance-of">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="el:constant"/>
        <xs:group ref="el:ClassExpression"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="related-to">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="el:constant"/>
        <xs:element ref="el:constant"/>
      </xs:sequence>
      <xs:attribute name="prop" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="conjunction">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="el:ClassExpression"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="exists">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="el:ClassExpression"/>
      </xs:sequence>
      <xs:attribute name="prop" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="atomic">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="constant">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== memotoro/xml-projects/trunk/xml-projects/xquery-wxs-project/el1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dltheory xmlns="http://www.cs.manchester.ac.uk/pgt/COMP60411/el" xmlns:el="http://www.cs.manchester.ac.uk/pgt/COMP60411/el"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.cs.manchester.ac.uk/pgt/COMP60411/el
    el.xsd">
    <author>Bijan Parsia</author>
    <last-revised-on>2010-02-12</last-revised-on>
    
    <comment>Sally is a good friend.</comment>
    <instance-of>
        <constant name="sally"/>
        <atomic name="Person"/>
    </instance-of>
    
    <comment>While I trust the following axiom is obvious, 
    you can also find it in Wikipedia.</comment>
    <web-source>http://en.wikipedia.org/wiki/Human</web-source>
    <subsumes>
        <atomic name="Human"/>
        <atomic name="LivingThing"/>
    </subsumes>
    
    <subsumes>
        <conjunction>
            <atomic name="Human"/>
            <exists prop="hasParent">
                <atomic name="Person"/>
            </exists>
        </conjunction>
        <atomic name="Person"/>
    </subsumes>
    
    <comment>This is true in common discussion, at least.</comment>
    <equivalent>
        <atomic name="Human"/>
        <atomic name="HomoSapiens"/>
    </equivalent>
    
    <instance-of>
        <constant name="sheeva"/>
        <atomic name="Human"/>
    </instance-of>
    
    <related-to prop="hasParent">
        <constant name="sheeva"/>
        <constant name="sally"/>
    </related-to>
</dltheory>
