=== memotoro/xml-projects/trunk/xml-projects/xlst-dtdx-project/dtdx-bjp.dtd
<!-- The root element.
	Productions taken from http://www.w3.org/TR/REC-xml/#NT-markupdecl
	
    markupdecl ::= elementdecl | AttlistDecl | Comment  -->
<!ELEMENT dtdx  (element | attlist | comment)*> 

<!-- Entities must be declared before use. See [47] and [48] -->
<!ENTITY % repat "(star|plus|opt)" >
<!ENTITY % nonrepat "(ref | choice | seq)">
<!ENTITY % cp "%nonrepat; | %repat;">
<!ENTITY % children "%cp;" >

<!-- [45]   	elementdecl	   ::=   	'<!ELEMENT' S Name S contentspec S? '>'	[VC: Unique Element Type Declaration]-->
<!ELEMENT element (empty | any | mixed | %children;)>
<!ATTLIST element name ID #REQUIRED>

<!-- Need both e-decl and e-ref. No need for attribute refs. -->
<!ELEMENT ref EMPTY>
<!ATTLIST ref to IDREF #REQUIRED>

<!-- [46]   	contentspec	   ::=   	'EMPTY' | 'ANY' | Mixed | children -->
<!ELEMENT empty EMPTY>
<!ELEMENT any EMPTY>

<!-- [51]   	Mixed	   ::=   	'(' S? '#PCDATA' (S? '|' S? Name)* S? ')*'
                                  | '(' S? '#PCDATA' S? ')' -->

<!--I leave the #PCDATA implied, as well as the alternation. It's just a list of refs
    It being empty makes it equivalent to the second alternative.-->
<!ELEMENT mixed (ref)*>

<!-- [47]   	children	   ::=   	(choice | seq) ('?' | '*' | '+')?
     [48]   	cp	   ::=   	(Name | choice | seq) ('?' | '*' | '+')?
     [49]   	choice	   ::=   	'(' S? cp ( S? '|' S? cp )+ S? ')'	[VC: Proper Group/PE Nesting]
     [50]   	seq	   ::=   	'(' S? cp ( S? ',' S? cp )* S? ') -->

<!ELEMENT choice ((%cp;), (%cp;)+)>
<!ELEMENT seq ((%cp;), (%cp;)+)>
<!ELEMENT opt %nonrepat;>
<!ELEMENT star %nonrepat;>
<!ELEMENT plus %nonrepat;>

<!-- [52]   	AttlistDecl	   ::=   	'<!ATTLIST' S Name AttDef* S? '>' -->
<!ELEMENT attlist (attdef)*>
<!ATTLIST attlist on IDREF #REQUIRED>

<!-- [53]   	AttDef	   ::=   	 S Name S AttType S DefaultDecl -->
<!-- <!ENTITY % atype "(string | tokenized | enumeration | notation)" >-->
<!ENTITY % atype "(string| tokenized | enumeration | notation )">
<!ENTITY % default "(required | implied | default)" >
<!ELEMENT attdef (%atype;, %default;)>
<!ATTLIST attdef name NMTOKEN #REQUIRED>

<!-- [54]   	AttType	   ::=   	 StringType | TokenizedType | EnumeratedType
[55]   	StringType	   ::=   	'CDATA'
[56]   	TokenizedType	   ::=   	'ID'	[VC: ID]
| 'IDREF'	[VC: IDREF]
| 'IDREFS'	[VC: IDREF]
| 'ENTITY'	[VC: Entity Name]
| 'ENTITIES'	[VC: Entity Name]
| 'NMTOKEN'	[VC: Name Token]
| 'NMTOKENS'	[VC: Name Token]
[58]   	NotationType	   ::=   	'NOTATION' S '(' S? Name (S? '|' S? Name)* S? ')'
[59]   	Enumeration	   ::=   	'(' S? Nmtoken (S? '|' S? Nmtoken)* S? ')'-->

<!ELEMENT string EMPTY> <!-- 'string' is more meaningful than 'CDATA' -->
<!ELEMENT tokenized EMPTY>
<!ATTLIST tokenized type (ID | IDREF | IDREFS | ENTITY | ENTITIES | NMTOKEN | NMTOKENS) #REQUIRED>
<!ELEMENT enumeration (nmtoken+)>
<!ELEMENT notation (nmtoken+)><!-- This is looser than required. NMTOKEN is more liberal than Name in the start char -->
<!ELEMENT nmtoken EMPTY>
<!ATTLIST nmtoken value NMTOKEN #REQUIRED>

<!-- [60]   	DefaultDecl	   ::=   	'#REQUIRED' | '#IMPLIED'
    | (('#FIXED' S)? AttValue) -->
 
<!ELEMENT required EMPTY>
<!ELEMENT implied EMPTY>
<!ELEMENT default EMPTY>
<!ATTLIST default value CDATA #IMPLIED
                  fixed (true | false) 'false'>


<!ELEMENT comment (#PCDATA)>

=== memotoro/xml-projects/trunk/xml-projects/xlst-dtdx-project/memo-psvi.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE dtdx SYSTEM "dtdx-bjp.dtd">

<!--
<dtdx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com dtdx-bjp.xsd">
-->    
<dtdx>
    <comment>Comment for 'a' element declaration</comment>
    <element name="a">
        <plus>
            <ref to="b"/>
        </plus>
    </element>

    <comment>Comment for 'c' element declaration with different nesting elements</comment>
    <element name="c">
        <plus>
            <seq>
                <ref to="a"/>
                <opt>
                    <choice>
                        <ref to="d"/>
                        <ref to="a"/>
                    </choice>
                </opt>
                <ref to="b"/>
            </seq>
        </plus>
    </element>

    <comment>Comment for 'd' element declaration with different nesting elements</comment>
    <element name="d">
        <opt>
            <choice>
                <ref to="c"/>
                <star>
                    <seq>
                        <ref to="d"/>
                        <ref to="a"/>
                    </seq>
                </star>
                <ref to="a"/>
            </choice>
        </opt>
    </element>   

    <comment>Comment for 'h' element declaration</comment>
    <element name="h">
        <ref to="b"/>        
    </element>

    <comment>Comment for 'b' element empty declaration but with attributes</comment>
    <element name="b">
        <empty/>
    </element>

    <comment>Comment for 'bb' element empty declaration</comment>
    <element name="bb">
        <empty/>
    </element>

    <comment>Comment for 'e' element any declaration</comment>
    <element name="e">
        <any/>
    </element>
    
    <comment>Comment for 'f' element mixed declaration</comment>
    <element name="f">
        <mixed>            
        </mixed>
    </element>

    <comment>Comment for 'ee' element any declaration but with attributes</comment>
    <element name="ee">
        <any/>
    </element>
    
    <comment>Comment for 'ff' element mixed declaration but with attributes</comment>
    <element name="ff">
        <mixed>            
        </mixed>
    </element>
    
    <comment>Comment for attributes declaration of 'b' element</comment>
    <attlist on="b">
        <attdef name="c">
            <string/>
            <implied/>
        </attdef>
        <attdef name="d">
            <tokenized type="IDREF"/>
            <required/>
        </attdef>
        <attdef name="e">
            <tokenized type="ENTITIES"/>
            <default fixed="true" value="DemoFixedValue"/>
        </attdef>       
    </attlist>
    
    <comment>Comment for attributes declaration of 'a' element</comment>
    <attlist on="a">
        <attdef name="f">
            <enumeration>
                <nmtoken value="A"/>
                <nmtoken value="B"/>
                <nmtoken value="C"/>
                <nmtoken value="D"/>
            </enumeration>
            <implied/>
        </attdef>
        <attdef name="g">
            <notation>
                <nmtoken value="Z"/>
                <nmtoken value="Y"/>
                <nmtoken value="X"/>
                <nmtoken value="W"/>
            </notation>
            <default fixed="false" value="W"/>
        </attdef>        
    </attlist>
     
    <comment>Comment for attributes declaration of 'ee' element</comment>
    <attlist on="ee">
        <attdef name="c">
            <string/>
            <implied/>
        </attdef>     
    </attlist>
     
    <comment>Comment for attributes declaration of 'ff' element</comment>
    <attlist on="ff">
        <attdef name="e">
            <tokenized type="ENTITIES"/>
            <default fixed="false" value="DemoFixedValue"/>
        </attdef>       
    </attlist>
     
</dtdx>

=== memotoro/xml-projects/trunk/xml-projects/xlst-dtdx-project/memo-calc1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dtdx SYSTEM "dtdx-bjp.dtd">
<dtdx>
    <element name="expression">
        <choice>
            <ref to="plus"/>
            <ref to="minus"/>
            <ref to="times"/>
            <ref to="int"/>
        </choice>
    </element>
    
    <element name="plus">
        <seq>
            <ref to="expression"/>
            <star>
                <ref to="expression"/>
            </star>            
        </seq>
    </element>
    
    <element name="times">
        <seq>
            <ref to="expression"/>
            <star>
                <ref to="expression"/>
            </star>            
        </seq>
    </element>
    
    <element name="minus">
        <seq>
            <ref to="expression"/>
            <ref to="expression"/>                       
        </seq>
    </element>

    <element name="int">
        <empty/>
    </element>
    
    <attlist on="int">
        <attdef name="value">
            <string/>
            <required/>
        </attdef>
    </attlist>
</dtdx>

=== memotoro/xml-projects/xml-projects/xlst-dtdx-project/memo-axioms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dtdx SYSTEM "dtdx-bjp.dtd">
<dtdx>
    <element name="dltheory">
        <seq>
            <ref to="author"/>
            <ref to="last-revised-on"/>
            <choice>
                <star>
                    <ref to="Axiom"/>
                </star>
                <star>
                    <ref to="Annotation"/>
                </star>
            </choice>
        </seq>
    </element>

    <element name="author">
        <mixed/>
    </element>

    <element name="last-revised-on">
        <mixed/>
    </element>

    <element name="Annotation">
        <choice>
            <ref to="comment"/>
            <ref to="web-source"/>
        </choice>
    </element>

    <element name="comment">
        <mixed/>
    </element>

    <element name="web-source">
        <mixed/>
    </element>

    <element name="Axiom">
        <choice>
            <ref to="equivalent"/>
            <ref to="subsumes"/>
            <ref to="instance-of"/>
            <ref to="related-to"/>
        </choice>
    </element>


    <element name="ClassExpression">
        <choice>
            <ref to="atomic"/>
            <ref to="conjunction"/>
            <ref to="exists"/>
        </choice>
    </element>

    <element name="equivalent">
        <seq>
            <ref to="ClassExpression"/>
            <star>
                <ref to="ClassExpression"/>
            </star>
        </seq>
    </element>

    <element name="subsumes">
        <seq>
            <ref to="ClassExpression"/>
            <ref to="ClassExpression"/>
        </seq>
    </element>

    <element name="instance-of">
        <seq>
            <ref to="constant"/>
            <ref to="ClassExpression"/>
        </seq>
    </element>

    <element name="related-to">
        <seq>
            <ref to="constant"/>
            <ref to="constant"/>
        </seq>
    </element>

    <element name="conjunction">
        <star>
            <ref to="ClassExpression"/>
        </star>
    </element>

    <element name="exists">
        <ref to="ClassExpression"/>
    </element>

    <attlist on="exists">
        <attdef name="prop">
            <string/>
            <required/>
        </attdef>
    </attlist>

    <element name="atomic">
        <empty/>
    </element>
    <attlist on="atomic">
        <attdef name="name">
            <string/>
            <required/>
        </attdef>
    </attlist>

    <element name="constant">
        <empty/>
    </element>
    <attlist on="constant">
        <attdef name="name">
            <string/>
            <required/>
        </attdef>
    </attlist>
</dtdx>
